/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aliaksandr.melas (https://sketchfab.com/alexandr.melas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-nebula-hdri-panorama-360-skydome-255203215c394bdb947c718b46515120
Title: Space nebula HDRI panorama 360 skydome
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useRef } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    [".003"]: THREE.MeshStandardMaterial;
  };
};

export default function SkyDome(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF(
    "/skydome/scene.gltf"
  ) as unknown as GLTFResult;
  const groupRef = useRef<THREE.Group>(null);
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials[".003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/skydome/scene.gltf");
